// The app's one entry point to the server API. Nothing else in the app
// imports http.ts directly.
import { setEncryptedSharesSource } from '../crypto/encrypted-shares'
import { httpApi } from './http'

export const api = httpApi

// The encrypted-share cache reads through the API client. Pushed in from here
// rather than imported there, because `api/http.ts` reads that module's own
// label logic and an import back the other way would close a cycle through
// this file, whose eager `api` const would then be captured undefined.
setEncryptedSharesSource(() => api.shareEncryptionList().then((r) => r.shares))

export type {
  SMBOutcome,
  SmbApplyReport,
  Entry,
  Perms,
  SessionInfo,
  SessionOidc,
  OidcConfig,
  OidcEndpoints,
  BatchResult,
  BatchItemResult,
  MoveReq,
  MovePreflight,
  OnConflict,
  Order,
  SortKey,
  AuthUser,
  LoginResult,
  UserInfo,
  AppPasswordInfo,
  ActiveSession,
  StorageReport,
  StorageShareUsage,
  IndexEstimate,
  IndexSettings,
  IndexStatus,
  HostEntry,
  HostListing,
  JobStatus,
  JobState,
  JobKindWire,
  JobListResponse,
  DirectUploadState,
  DirectUploadPartURL,
  DirectUploadReservation,
  DirectUploadStatus,
  DirectUploadCompletedPart,
  DirectUploadCreateReq,
  DirectUploadCompleteReq,
  DirectUploadCompleteResult,
  JobAction,
  AdminUser,
  AdminUserOidc,
  AdminOidcUnlinkResult,
  ReadFileResponse,
  TrashEntry,
  ShareLinkInfo,
  OwnedShareLinkInfo,
  ShareLinkCreateReq,
  ShareLinkPatchReq,
  PermsReq,
  AdminShare,
  ShareEncryption,
  CreateShareReq,
  UpdateShareReq,
  ShareBackend,
  ShareS3Config,
  ShareVeracryptConfig,
  AdminGrant,
  GrantPermName,
  GrantPrincipal,
  CreateGrantReq,
  UpdateGrantReq,
  AdminGroup,
  CreateGroupReq,
  UpdateGroupReq,
  AuditRow,
  AuditQuery,
  AuditPage,
  AdminLogRecord,
  AdminLogQuery,
  AdminLogPage,
  AdminLogsTimelineQuery,
  AdminLogsTimelineBucket,
  AdminLogsTimeline,
  UploadSettingsReq,
  UploadSettingsResp,
  SettingsSource,
  SettingsField,
  SettingsSnapshot,
  SystemHealth,
  SystemRestartResult,
  DownloadTicket,
  Hop,
  ApplyOutcome,
  SmbSettingsReq,
  SearchSettingsReq,
  ArchiveSettingsReq,
  NetworkSettingsReq,
  OidcSettingsReq,
  DbSettingsReq,
  HomesSettingsReq,
  WatchSettingsReq,
  ThumbnailSettingsReq
} from './types'
export { ALL_GRANT_PERMS, ALL_LOG_LEVELS } from './types'
export { ApiError } from './types'
export type { ListOpts, SearchDone, SearchHit, SearchProgress, SearchRequest } from './types'
