// Stowcloud's adapter for the public rclone-crypt codec. Share lookup,
// labels, server policy, and UI/session behavior remain product-owned here;
// format, key lifecycle, streaming, range, and resume semantics are public.
export {
  BLOCK_SIZE,
  HEADER_SIZE,
  MAX_ENCRYPTABLE_BYTES,
  NONCE_BYTES,
  RCLONE_CRYPT_MAGIC,
  RESUME_METADATA_VERSION,
  SourceChangedError,
  FileTooLargeError,
  LockedSessionError,
  ResumeMetadataError,
  SessionChangedError,
  WrongPassphraseError,
  checkVerifier,
  ciphertextSpanForRange,
  createResumeMetadata,
  decryptDownload,
  decryptPlaintextRange,
  decryptStream,
  decryptTransform,
  deriveKeys,
  encryptForUpload,
  encryptStreamForKey,
  generateSalt,
  isUnlocked,
  lock,
  makeVerifier,
  openSessionValue,
  plaintextSizeFromCiphertextSize,
  sealSessionValue,
  sourceCommitment,
  tryPlaintextSize,
  unlock,
  validateResumeMetadata
} from '@stowcloud/rclone-crypt'
export type {
  CiphertextSpan,
  DecryptStreamOptions,
  DerivedKeys,
  EncryptStreamOptions,
  ResumeMetadata,
  ResumeMetadataExpectation
} from '@stowcloud/rclone-crypt'
