import { useEffect, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { destinationProblem } from '../api/path-utils'
import { statQuery } from '../query/files'
import { sessionQuery } from '../query/session'
import { useI18n } from '../i18n/use-i18n'
import { Button } from './Button'
import { BrowseDialog } from './browse-dialog'
import { FileTreeItem } from './FileTreeItem'
export function DestinationPickerDialog({ open, sources, canCopy, canMove, onClose, onPick }: { open: boolean; sources: string[]; canCopy: boolean; canMove: boolean; onClose: () => void; onPick: (dest: string, mode: 'move' | 'copy') => void }) {
  const { t } = useI18n(); const session = useQuery(sessionQuery()); const roots = (session.data?.roots ?? []).map((root) => ({ path: `/${root.label}`, name: root.label })); const [selected, setSelected] = useState<string | null>(null); const [activeDescendant, setActiveDescendant] = useState<string | undefined>(undefined); const stat = useQuery({ ...statQuery(selected ?? ''), enabled: open && selected !== null }); const problem = selected ? destinationProblem(selected, sources) : null; const writable = stat.data?.perms.create ?? false; const copy = canCopy && selected !== null && problem !== 'into_itself' && writable; const move = canMove && selected !== null && problem === null && writable
  useEffect(() => { if (!open) { setSelected(null); setActiveDescendant(undefined) } }, [open])
  const treeFocus = (event: React.FocusEvent<HTMLUListElement>) => { const tree = event.currentTarget; const target = event.target as HTMLElement; const labelTarget = target.closest<HTMLElement>('[data-tree-label], [data-tree-more]'); if (labelTarget) { tree.tabIndex = -1; if (labelTarget.id) setActiveDescendant(labelTarget.id); return } const first = tree.querySelector<HTMLElement>('[aria-current="page"] [data-tree-label], [data-tree-label], [data-tree-more]'); if (first) { tree.tabIndex = -1; if (first.id) setActiveDescendant(first.id); first.focus() } }
  return <BrowseDialog open={open} title={t('dest.move_or_copy')} onClose={onClose} actions={<><Button variant="text" onClick={onClose}>{t('common.cancel')}</Button>{canCopy ? <Button variant="outlined" disabled={!copy} onClick={() => selected && onPick(selected, 'copy')}>{t('common.copy')}</Button> : null}{canMove ? <Button disabled={!move} onClick={() => selected && onPick(selected, 'move')}>{t('common.move')}</Button> : null}</>}><p>{t('dest.choose_destination_folder', { count: sources.length })}</p><ul role="tree" tabIndex={0} aria-label={t('dest.destination_folder')} aria-activedescendant={activeDescendant} onFocusCapture={treeFocus}>{roots.map((root, index) => <FileTreeItem key={root.path} path={root.path} name={root.name} depth={0} currentPath={selected ?? ''} onNavigate={setSelected} initial={index === 0} position={index + 1} setSize={roots.length} />)}</ul>{problem === 'into_itself' ? <p>{t('dest.cannot_move_folder_into_itself')}</p> : problem === 'same_folder' ? <p>{t('dest.already_in_this_folder')}</p> : selected !== null && stat.data && !writable ? <p>{t('dest.cannot_write_into_folder')}</p> : selected === null ? <p>{t('dest.no_folder_chosen')}</p> : <p>{selected}</p>}</BrowseDialog>
}
