import { useEffect, useMemo, useRef, useState } from 'react'
import { useInfiniteQuery } from '@tanstack/react-query'
import { dirListQuery, dirViewOf } from '../query/files'
import { joinPath } from '../api/path-utils'
import { useI18n } from '../i18n/use-i18n'
import { Icon } from './Icon'
import './browse-ui.css'

export interface FileTreeItemProps { path: string; name: string; depth: number; currentPath: string; onNavigate: (path: string) => void; position?: number; setSize?: number; initial?: boolean }
export function FileTreeItem({ path, name, depth, currentPath, onNavigate, position, setSize, initial = false }: FileTreeItemProps) {
  const { t } = useI18n(); const [expanded, setExpanded] = useState(false); const label = useRef<HTMLButtonElement>(null); const li = useRef<HTMLLIElement>(null)
  const query = useInfiniteQuery({ ...dirListQuery(path, { key: 'name', order: 'asc' }), enabled: expanded }); const directory = dirViewOf(query.data?.pages); const children = useMemo(() => directory.entries.filter((e) => e.kind === 'dir'), [directory.entries]); const active = currentPath === path; const ancestor = !active && currentPath.startsWith(`${path}/`); const groupId = `sc-tree-group-${encodeURIComponent(path).replace(/%/g, '_')}`
  useEffect(() => { if (ancestor && !expanded) setExpanded(true) }, [ancestor, expanded]); useEffect(() => { if (!ancestor || !expanded || !query.hasNextPage || query.isFetchingNextPage) return; const contains = children.some((child) => { const p = joinPath(path, child.name); return currentPath === p || currentPath.startsWith(`${p}/`) }); if (!contains) void query.fetchNextPage() }, [ancestor, expanded, query.hasNextPage, query.isFetchingNextPage, children, currentPath, path])
  const focusSibling = (delta: number) => { const tree = label.current?.closest('[role=tree]'); if (!tree) return; const items = [...tree.querySelectorAll<HTMLElement>('[data-tree-label], [data-tree-more]')]; const index = items.indexOf(label.current as HTMLElement); items[Math.min(Math.max(index + delta, 0), items.length - 1)]?.focus() }
  const keyDown = (event: React.KeyboardEvent<HTMLButtonElement>) => { if (event.key === 'ArrowDown') { event.preventDefault(); focusSibling(1) } else if (event.key === 'ArrowUp') { event.preventDefault(); focusSibling(-1) } else if (event.key === 'ArrowRight') { event.preventDefault(); if (!expanded) setExpanded(true); else children[0] && document.querySelector<HTMLButtonElement>(`[data-tree-node="${CSS.escape(joinPath(path, children[0].name))}"] [data-tree-label]`)?.focus() } else if (event.key === 'ArrowLeft') { event.preventDefault(); if (expanded) setExpanded(false); else (li.current?.parentElement?.closest('[role=treeitem]')?.querySelector('[data-tree-label]') as HTMLElement | null)?.focus() } else if (event.key === '*') { event.preventDefault(); for (const item of li.current?.parentElement?.children ?? []) { const toggle = (item as HTMLElement).querySelector<HTMLButtonElement>(':scope > .sc-tree-row [data-tree-toggle][aria-expanded="false"]'); toggle?.click() } } else if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onNavigate(path); setExpanded(true) } else if (event.key === 'Home' || event.key === 'End') { event.preventDefault(); const tree = label.current?.closest('[role=tree]'); const items = tree ? [...tree.querySelectorAll<HTMLElement>('[data-tree-label], [data-tree-more]')] : []; (event.key === 'Home' ? items[0] : items.at(-1))?.focus() } }
  return <li ref={li} role="treeitem" aria-expanded={expanded} aria-selected={active} aria-current={active ? 'page' : undefined} aria-level={depth + 1} aria-posinset={position} aria-setsize={setSize} aria-busy={query.isPending || query.isFetchingNextPage ? 'true' : undefined} data-tree-node={path}><div className={`sc-tree-row${active ? ' sc-tree-row--active' : ''}${ancestor ? ' sc-tree-row--ancestor' : ''}`} style={{ paddingInlineStart: depth * 16 + 8 }}><button type="button" className="sc-tree-row__twisty" data-tree-toggle tabIndex={-1} aria-expanded={expanded} aria-controls={expanded ? groupId : undefined} aria-label={expanded ? t('tree.collapse', { name }) : t('tree.expand', { name })} onClick={() => { setExpanded(!expanded); label.current?.focus() }}><span className={`sc-tree-row__twisty-icon${expanded ? ' sc-tree-row__twisty-icon--expanded' : ''}`} aria-hidden="true"><Icon name="chevron_right" size={16} /></span></button><button id={`sc-tree-label-${encodeURIComponent(path).replace(/%/g, '_')}`} ref={label} type="button" className="sc-tree-row__label" data-tree-label tabIndex={initial ? 0 : -1} onClick={() => { onNavigate(path); setExpanded(true) }} onKeyDown={keyDown}><Icon name="folder" /><span className="sc-tree-row__name">{name}</span></button></div>{expanded ? query.isPending ? <p className="sc-tree-row__status" role="status">{t('common.loading')}</p> : query.isError ? <p className="sc-tree-row__status sc-tree-row__status--error" role="alert">{t('tree.could_not_load_subfolders')}</p> : <>{children.length ? <ul id={groupId} role="group">{children.map((child, i) => <FileTreeItem key={child.name} path={joinPath(path, child.name)} name={child.name} depth={depth + 1} currentPath={currentPath} onNavigate={onNavigate} position={i + 1} setSize={directory.dirs} />)}</ul> : <p className="sc-tree-row__status">{t('tree.no_subfolders')}</p>}{query.hasNextPage ? <button type="button" className="sc-tree-row__more" data-tree-more tabIndex={-1} aria-busy={query.isFetchingNextPage ? 'true' : undefined} onClick={() => void query.fetchNextPage()}>{query.isFetchingNextPage ? t('common.loading') : t('common.continue')}</button> : null}</> : null}</li>
}
