#!/usr/bin/env bash
# A development server, reachable over the tailnet.
#
#   bash scripts/dev.sh            # start it, print where to go
#   bash scripts/dev.sh --fresh    # throw the data directory away first
#
# It replaces a smoke script that drove the Rust binary this tree no longer
# has, with a config in a format the Go build does not parse.
#
# What it is for: looking at the shipped interface in a real browser, on a
# phone or another machine, over the tailnet rather than loopback. Everything
# it does is a development convenience and none of it is how a deployment is
# configured; deploy/sc.toml.example is that.
set -uo pipefail
cd "$(dirname "$0")/.."

DIR=${SC_DEV_DIR:-.dev}
PORT=${SC_DEV_PORT:-18443}

if [ "${1:-}" = "--fresh" ]; then
  echo "==> removing $DIR"
  rm -rf "$DIR"
fi

# The tailnet name, which has to be in the certificate's SANs and in the host
# allow-list. The server refuses a Host header it was not configured for, so a
# name discovered at request time would defeat the guard it is asked about.
TSNAME=$(tailscale status --json 2>/dev/null \
  | python3 -c 'import json,sys; print(json.load(sys.stdin).get("Self",{}).get("DNSName","").rstrip("."))' 2>/dev/null)
TSIP=$(tailscale ip -4 2>/dev/null | head -1)

if [ -z "$TSNAME" ]; then
  echo "no tailnet name; serving on localhost only" >&2
  TSNAME=localhost
fi

mkdir -p "$DIR"/data "$DIR"/shares/documents/notes "$DIR"/shares/pictures

# A share with something in it, so the browse screen has rows to draw.
[ -f "$DIR/shares/documents/readme.txt" ] || cat > "$DIR/shares/documents/readme.txt" <<'TXT'
A file in the development share.
TXT
[ -f "$DIR/shares/documents/notes/todo.md" ] || cat > "$DIR/shares/documents/notes/todo.md" <<'TXT'
# Notes

A second file, one directory down.
TXT

# Written every run: the tailnet name can change, and a stale host list is a
# server that refuses the address it is being opened at.
#
# The listener is on every interface rather than loopback, which is the whole
# point of this script. It is bounded by the tailnet: the machine's own
# firewall is what decides who reaches the port, and the host guard refuses
# anything addressed by a name that is not below.
cat > "$DIR/sc.toml" <<TOML
# Generated by scripts/dev.sh. Not a deployment example; see
# deploy/sc.toml.example for that.
[server]
data_dir = "$PWD/$DIR/data"
listen = "0.0.0.0:$PORT"

[http]
app_hosts = ["$TSNAME", "localhost"]
content_hosts = ["localhost"]

[rate]
# Raised for a person clicking around with a hot reload in front of them. The
# shipped default is far lower and is the one a deployment gets.
per_sec = 200
burst = 500

[security]
# Off, because the sandbox refuses a data directory under a home directory on
# some kernels and this is a scratch tree rather than a deployment. A
# deployment leaves this alone.
hardening = "off"

[[shares]]
name = "documents"
host_path = "$PWD/$DIR/shares/documents"

[[shares]]
name = "pictures"
host_path = "$PWD/$DIR/shares/pictures"
TOML

# A certificate the tailnet's own CA signed, when tailscale will issue one.
#
# The self-signed pair the server mints otherwise is fine in a desktop browser,
# which asks once and remembers. It is not fine on a phone: Android refuses an
# untrusted certificate for subresources outright, so the shell loads, every
# script and stylesheet fails, and what you get is a blank screen with nothing
# on it saying why. That is worse than a refusal.
#
# The server reads data/tls/cert.pem when one is there and self-signs when it
# is not, so this only has to put the file in place.
# Asked for on every run, not only when the file is missing. The server
# self-signs on first start, so after one run there is always a cert.pem there
# and a check for its absence never fires again: the message would then say the
# certificate is trusted while the self-signed one is still being served.
#
# tailscale writes the pair only when it has one to write, and it is cheap to
# ask: the daemon caches the certificate and renews it in the background.
CERT_TRUSTED=
if [ "$TSNAME" != localhost ]; then
  mkdir -p "$DIR/data/tls"
  # Announced before it runs, and bounded. Issuing the first certificate for a
  # name goes out to the CA and takes around half a minute; refusing takes as
  # long. Either way it is a silent wait, and a script that prints "removing
  # .dev" and then says nothing for thirty seconds reads as one that has hung.
  echo "==> asking tailscale for a certificate (up to 60s the first time)"
  if timeout 60 tailscale cert --cert-file "$DIR/data/tls/cert.pem" \
       --key-file "$DIR/data/tls/key.pem" "$TSNAME" >/dev/null 2>&1; then
    echo "    got one, signed by the tailnet's CA"
    CERT_TRUSTED=1
  else
    # Not fatal: the server mints its own on first start. What that costs on a
    # phone is in the note at the end.
    echo "    none; the server will self-sign"
    rm -f "$DIR/data/tls/cert.pem" "$DIR/data/tls/key.pem"
  fi
fi

echo "==> building the frontend"
if [ -d web/node_modules ]; then
  (cd web && npm run build) >/dev/null || { echo "the frontend build failed" >&2; exit 1; }
else
  echo "no web/node_modules; run npm ci in web/ for the interface" >&2
fi

echo "==> building the binary"
BIN="$PWD/$DIR/stowcloud"
(cd go && CGO_ENABLED=0 go build -tags embed_ui -o "$BIN" ./cmd/stowcloud) \
  || { echo "the build failed" >&2; exit 1; }

echo "==> serving"
"$BIN" serve "$DIR/sc.toml" > "$DIR/log" 2>&1 &
SERVER=$!
echo "$SERVER" > "$DIR/pid"

# Give it long enough to bind, open its databases and mint a setup token.
for _ in $(seq 1 40); do
  sleep 0.25
  kill -0 "$SERVER" 2>/dev/null || break
  grep -q "listening" "$DIR/log" 2>/dev/null && break
done

if ! kill -0 "$SERVER" 2>/dev/null; then
  echo
  echo "the server exited instead of serving:" >&2
  sed -n '1,40p' "$DIR/log" >&2
  exit 1
fi

TOKEN=$(grep -oE 'setup token \(valid[^)]*\): [a-f0-9]+' "$DIR/log" | tail -1 | awk '{print $NF}')

echo
echo "  https://$TSNAME:$PORT/"
[ -n "$TSIP" ] && echo "  https://$TSIP:$PORT/    (the certificate names $TSNAME, so this one warns)"
echo
if [ -n "$TOKEN" ]; then
  echo "  first run: the setup screen wants this token, and it expires in 15 minutes"
  echo "    $TOKEN"
  echo
  echo "  a token that has expired is a restart away: bash scripts/dev.sh"
else
  echo "  already set up; sign in with the account made on the first run"
fi
echo
if [ -n "$CERT_TRUSTED" ]; then
  echo "  The certificate is the tailnet CA's, so no browser warns."
else
  echo "  The certificate is self-signed: tailscale would not issue one without"
  echo "  root. A desktop browser asks once and remembers. A phone does not: it"
  echo "  refuses the subresources and draws a blank page with no error on it,"
  echo "  which is what an empty screen on a phone means here."
  echo
  echo "  For a real certificate, once:"
  echo "    sudo tailscale set --operator=\$USER"
  echo "  then: bash scripts/dev.sh --fresh"
fi
echo
echo "  log:  $DIR/log"
echo "  stop: kill \$(cat $DIR/pid)"
