#!/usr/bin/env node
// Regenerate THIRD-PARTY-NOTICES.md from the two dependency trees that end up
// inside the shipped binary. Run from the repo root:
//
//   cargo metadata --format-version 1 --locked > .notices-meta.json
//   node scripts/gen-notices.mjs
//   rm .notices-meta.json
//
// Hand-maintaining this list is not possible: 348 Rust crates and 62 npm
// packages, each with its own copyright line, and MIT/BSD/ISC all require the
// notice to travel with the copy. The file is generated so it can be true.
//
// Scope. Rust: every non-workspace package in the resolved graph — the release
// binary is statically linked, so the graph is the artifact. npm: only what the
// browser actually downloads, which is *not* the same as `dependencies`. Vite
// compiles with rollup/esbuild/postcss/the svelte compiler and ships none of
// them, so the shipped set is listed explicitly below rather than derived.

import { readFileSync, readdirSync, existsSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { createHash } from 'node:crypto'

const META = '.notices-meta.json'
const OUT = 'THIRD-PARTY-NOTICES.md'
const NM = 'web/node_modules'

// Packages whose code or data reaches the browser. Everything else in
// `web/package.json` is a build tool.
const JS_RUNTIME = [
  'svelte', '@sveltejs/kit', 'esm-env', 'clsx', 'devalue',
  'm3-svelte', '@ktibow/iconset-material-symbols',
  '@ktibow/material-color-utilities-nightly',
  '@fontsource-variable/google-sans-flex',
  'codemirror', '@marijn/find-cluster-break', 'style-mod', 'w3c-keyname', 'crelt',
]
for (const scope of ['@codemirror', '@lezer']) {
  for (const n of readdirSync(join(NM, scope))) JS_RUNTIME.push(`${scope}/${n}`)
}

const LICENSE_FILE = /^(licen[sc]e|copying|notice|unlicense)/i

/** All licence-ish files in a directory, as {name, text}. */
function licenseTexts(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((n) => LICENSE_FILE.test(n) && !/\.(js|ts|mjs|cjs|d\.ts)$/i.test(n))
    .sort()
    .map((n) => {
      try {
        return { name: n, text: readFileSync(join(dir, n), 'utf8').replace(/\r\n/g, '\n').trim() }
      } catch {
        return null
      }
    })
    .filter(Boolean)
}

// Identical texts are pooled and printed once; a Rust workspace pulls in
// hundreds of byte-identical MIT copies and reprinting each is noise, not
// compliance.
const pool = new Map() // sha1 -> {id, text, users:[]}
function intern(text, user) {
  const h = createHash('sha1').update(text).digest('hex')
  let e = pool.get(h)
  if (!e) { e = { id: pool.size + 1, text, users: [] }; pool.set(h, e) }
  e.users.push(user)
  return e.id
}

const rows = [] // {eco, name, version, license, url, texts:[id]}

// --- Rust ------------------------------------------------------------------
const meta = JSON.parse(readFileSync(META, 'utf8'))
const crates = meta.packages
  .filter((p) => (p.source || '').length > 0)
  .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version))
for (const p of crates) {
  const dir = dirname(p.manifest_path)
  const files = licenseTexts(dir)
  rows.push({
    eco: 'rust',
    name: p.name,
    version: p.version,
    license: p.license || (p.license_file ? `see ${p.license_file}` : 'NOT DECLARED'),
    url: p.repository || `https://crates.io/crates/${p.name}`,
    texts: files.map((f) => intern(f.text, `${p.name} ${p.version}`)),
  })
}

// --- npm -------------------------------------------------------------------
for (const name of JS_RUNTIME.sort()) {
  const dir = join(NM, name)
  const pj = join(dir, 'package.json')
  if (!existsSync(pj)) throw new Error(`${name}: not installed — run npm ci in web/ first`)
  const j = JSON.parse(readFileSync(pj, 'utf8'))
  const files = licenseTexts(dir)
  const repo = typeof j.repository === 'string' ? j.repository : j.repository?.url || ''
  rows.push({
    eco: 'npm',
    name,
    version: j.version,
    license: j.license || 'NOT DECLARED',
    url: repo.replace(/^git\+/, '').replace(/\.git$/, '') || `https://www.npmjs.com/package/${name}`,
    texts: files.map((f) => intern(f.text, `${name} ${j.version}`)),
  })
}

// --- emit ------------------------------------------------------------------
const undeclared = rows.filter((r) => !r.texts.length)
const out = []
out.push('# Third-party notices')
out.push('')
out.push('Stowcloud ships as one binary. The Rust dependency graph is statically')
out.push('linked into it and the built frontend — including the webfont — is embedded')
out.push('by `rust_embed` at compile time, so everything listed here is *redistributed*,')
out.push('not merely used at build time. MIT, BSD, ISC and Apache-2.0 all require their')
out.push('notice to travel with the copy; this file is that notice.')
out.push('')
out.push('Generated by `scripts/gen-notices.mjs`. Do not edit by hand — regenerate it')
out.push('when a dependency is added, removed, or bumped.')
out.push('')
out.push(`Components: ${rows.filter((r) => r.eco === 'rust').length} Rust crates, ` +
         `${rows.filter((r) => r.eco === 'npm').length} npm packages. ` +
         `Distinct licence texts: ${pool.size}.`)
out.push('')
if (undeclared.length) {
  out.push('> **No licence file shipped in the package** (the SPDX expression in its')
  out.push('> manifest is the only statement of terms): ' +
           undeclared.map((r) => `\`${r.name} ${r.version}\``).join(', ') + '.')
  out.push('')
}
out.push('Stowcloud itself is AGPL-3.0-or-later; see [`LICENSE`](LICENSE).')
out.push('')
out.push('---')
out.push('')

for (const [eco, title] of [['rust', 'Rust crates (statically linked)'], ['npm', 'npm packages (embedded frontend)']]) {
  out.push(`## ${title}`)
  out.push('')
  out.push('| Package | Version | Licence | Texts |')
  out.push('|---|---|---|---|')
  for (const r of rows.filter((x) => x.eco === eco)) {
    const t = r.texts.length ? r.texts.map((i) => `[#${i}](#licence-text-${i})`).join(', ') : '—'
    out.push(`| [${r.name}](${r.url}) | ${r.version} | ${r.license} | ${t} |`)
  }
  out.push('')
}

out.push('---')
out.push('')
out.push('## Licence texts')
out.push('')
for (const e of [...pool.values()].sort((a, b) => a.id - b.id)) {
  out.push(`### Licence text ${e.id}`)
  out.push('')
  out.push(`Applies to: ${e.users.map((u) => `\`${u}\``).join(', ')}`)
  out.push('')
  out.push('```')
  out.push(e.text.replace(/```/g, "'''"))
  out.push('```')
  out.push('')
}

writeFileSync(OUT, out.join('\n'))
console.log(`${OUT}: ${rows.length} components, ${pool.size} licence texts, ${out.join('\n').length} bytes`)
